---

- name: "Criando o droplet"
  digital_ocean_droplet: 
    state: present
    name: "{{ droplet_host_name }}"
    size: "{{ droplet_droplet_size }}"
    region: "{{ droplet_region }}"
    image: "{{ droplet_droplet_image }}"
    oauth_token: "{{ droplet_do_token }}"
    wait_timeout: "{{ droplet_wait_timeout }}"
    unique_name: "{{ droplet_unique_name }}"
    private_networking: "{{ droplet_private_networking }}"
    ssh_keys: "{{ droplet_ssh_keys|join(',') }}"
  register: my_droplet

- name: "Informação do droplet"
  debug:
    msg: "IP Address é: {{ my_droplet.data.ip_address }}"

- name: "Set uma variavel fact para registrar a variavel droplet_ip"
  set_fact:
    droplet_ip: "{{ my_droplet.data.ip_address }}"

- name: "Adicionando o novo host ao Ansible inventory"  
  add_host:
    name: "{{ my_droplet.data.ip_address }}"
    groups: docker

- name: "Aguardando o servidor responder SSH"
  wait_for:
    host: "{{ my_droplet.data.ip_address }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
